-----------------------------------------------------------
-- NOTES: This file is run on app start after exports are done inside 
-- 		  the engine (once per context created)
-----------------------------------------------------------

-- set up path
package.path = package.path .. ";script\\?.lua;script\\country\\?.lua"
package.path = package.path .. ";common\\?.lua"

--require('hoi') -- already imported by game, contains all exported classes
require('utils')
require('defines')
require('ai_country')
require('ai_foreign_minister')
require('ai_intelligence_minister')
require('ai_politics_minister')
require('ai_production_minister')
require('ai_support_functions')
require('ai_tech_minister')
require('ai_trade')
require('ai_license')

-- Default Files
require('DEFAULT_LAND')
require('DEFAULT_MIXED')

-- load country specific AI modules.
-- Majors
require('AUH')
require('ENG')
require('FRA')
require('GER')
require('ITA')
require('JAP')
require('RUS')
require('SOV')
require('TUR')
require('USA')
require('WHR')

-- Minors (Alphabetized)
require('ARG')
require('AST')
require('BEL')
require('BOL')
require('BRA')
require('BUL')
require('CAN')
require('CGX')
require('CHC')
require('CHI')
require('CHL')
require('COL')
require('COS')
require('CSX')
require('CXB')
require('CYN')
require('DEN')
require('DOM')
require('ECU')
require('FIN')
require('GRE')
require('GUA')
require('HAI')
require('HJZ')
require('HOL')
require('HON')
require('HUN')
require('LIB')
require('LUX')
require('MAN')
require('MEN')
require('MEX')
require('NIC')
require('NOR')
require('NZL')
require('OMN')
require('PAN')
require('PAR')
require('PER')
require('POL')
require('POR')
require('PRU')
require('QIN')
require('ROM')
require('SAF')
require('SAL')
require('SCH')
require('SER')
require('SIA')
require('SIK')
require('SPA')
require('SPR')
require('SWE')
require('TIB')
require('URU')
require('VEN')
require('VIC')
require('YUG')
